export const CATEGORIES = [
    { id: '1', type: 'business', key: 'pharmacies', icon: 'pill.fill' },
    { id: '2', type: 'business', key: 'automotive', icon: 'car.fill' },
    { id: '3', type: 'business', key: 'books', icon: 'book.fill' },
    { id: '4', type: 'business', key: 'cameras', icon: 'camera.fill' },
    { id: '5', type: 'business', key: 'electronics', icon: 'desktopcomputer' },
    { id: '6', type: 'business', key: 'fashion', icon: 'tshirt.fill' },
    { id: '7', type: 'business', key: 'real-estate', icon: 'house.fill' },
    { id: '8', type: 'business', key: 'deals', icon: 'tag.fill' },
    { id: '9', type: 'business', key: 'featured', icon: 'star.fill' },
    { id: '10', type: 'business', key: 'travel', icon: 'globe' },
    { id: '11', type: 'business', key: 'mobile', icon: 'phone.fill' },
    { id: '12', type: 'business', key: 'local', icon: 'map.fill' },
    { id: '13', type: 'business', key: 'events', icon: 'calendar' },
] as const;