export const CATEGORIES = [
    { id: '1', name: 'Pharmacies', icon: 'pill.fill', path: '/pharmacies/list' },
    { id: '2', name: 'Automotive', icon: 'car.fill', path: '/automotive/list' },
    { id: '3', name: 'Books', icon: 'book.fill', path: '/books/list' },
    { id: '4', name: 'Cameras', icon: 'camera.fill', path: '/cameras/list' },
    { id: '5', name: 'Electronics', icon: 'desktopcomputer', path: '/electronics/list' },
    { id: '6', name: 'Fashion', icon: 'tshirt.fill', path: '/fashion/list' },
    { id: '7', name: 'Real Estate', icon: 'house.fill', path: '/real-estate/list' },
    { id: '8', name: 'Deals', icon: 'tag.fill', path: '/deals/list' },
    { id: '9', name: 'Featured', icon: 'star.fill', path: '/featured/list' },
    { id: '10', name: 'Travel', icon: 'globe', path: '/travel/list' },
    { id: '11', name: 'Mobile', icon: 'phone.fill', path: '/mobile/list' },
    { id: '12', name: 'Local', icon: 'map.fill', path: '/local/list' },
    { id: '13', name: 'Events', icon: 'calendar', path: '/events/list' },
] as const;